name: Build and Push Docker Image for Hello, World

on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: dotnet restore HelloWorld/HelloWorldWebServer/HelloWorldWebServer.sln

    - name: Build the project 
      run: dotnet build --configuration Release --no-restore HelloWorld/HelloWorldWebServer/HelloWorldWebServer.sln

    - name: Publish the project
      run: dotnet publish -c Release HelloWorld/HelloWorldWebServer/HelloWorldWebServer.sln

    - name: Build Docker image
      run: docker build -t cs399.azurecr.io/helloworld:${{ github.sha}} HelloWorld/HelloWorldWebServer/Dockerfile
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: cs399.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image
      run: docker push cs399.azure.io/helloworld:${{ github.sha }}
